[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:43:54.158 [DiscoveryClient-HeartbeatExecutor-0] INFO  org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec#execute:113 -Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {}->http://121.37.97.46:8761
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:43:57.371 [DiscoveryClient-CacheRefreshExecutor-0] INFO  org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec#execute:113 -Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {}->http://121.37.97.46:8761
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:48:32.677 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#?:? -Resolving eureka endpoints via configuration
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:51:58.340 [DiscoveryClient-CacheRefreshExecutor-0] INFO  org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec#?:? -Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {}->http://121.37.97.46:8761
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:52:28.408 [DiscoveryClient-CacheRefreshExecutor-0] INFO  org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec#execute:113 -Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {}->http://121.37.97.46:8761
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:53:32.678 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:53:58.598 [DiscoveryClient-CacheRefreshExecutor-0] INFO  org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec#execute:113 -Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {}->http://121.37.97.46:8761
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:54:11.685 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7d1123bf (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:54:16.687 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@59d64a67 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:54:21.692 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@44809565 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:54:26.864 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@5bd9eae5 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:54:31.867 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#isConnectionDead:179 -HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1dfa11af (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 21:58:32.680 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:00:00.329 [pool-14-thread-243] INFO  com.fit2cloud.quartz.CloudAccountSyncJob$RenewInstance#?:? -Method[run][开始自动续费任务]
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:00:00.454 [pool-14-thread-243] INFO  com.fit2cloud.quartz.CloudAccountSyncJob$RenewInstance#?:? -Method[run][结束自动续费任务]
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:02:57.472 [DiscoveryClient-HeartbeatExecutor-0] INFO  org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec#execute:113 -Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {}->http://121.37.97.46:8761
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:03:32.681 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#getClusterEndpoints:43 -Resolving eureka endpoints via configuration
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:08:32.693 [AsyncResolver-bootstrap-executor-0] INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver#?:? -Resolving eureka endpoints via configuration
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:09:51.784 [OkHttp ConnectionPool] WARN  okhttp3.OkHttpClient#?:? -A connection to https://shop.livepartner.fans/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.800 [SpringApplicationShutdownHook] INFO  org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry#?:? -Unregistering application VM-SERVICE with eureka with status DOWN
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.801 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Saw local status change event StatusChangeEvent [timestamp=1753798361801, current=DOWN, previous=UP]
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.807 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.Server#?:? -Stopped Server@1c6912db{STOPPING}[11.0.15,sto=0]
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.810 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.AbstractConnector#?:? -Stopped ServerConnector@2c8d537e{HTTP/1.1, (http/1.1)}{0.0.0.0:9911}
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.811 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler.application#?:? -Destroying Spring FrameworkServlet 'dispatcherServletRegistration'
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.813 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler#?:? -Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@543982ac{application,/,[file:///C:/Users/%E9%A2%9C%E8%B1%AA%E7%94%B7/AppData/Local/Temp/jetty-docbase.9911.4815133104584791198/, jar:file:/D:/data/.m2/org/webjars/swagger-ui/4.18.2/swagger-ui-4.18.2.jar!/META-INF/resources],STOPPED}
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.826 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service paused.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.826 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.Server#?:? -Stopped Server@3355d9ba{STOPPING}[11.0.15,sto=0]
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.827 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.AbstractConnector#?:? -Stopped ServerConnector@194eae3e{HTTP/1.1, (http/1.1)}{0.0.0.0:9011}
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.829 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler.application#?:? -Destroying Spring FrameworkServlet 'dispatcherServlet'
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.829 [SpringApplicationShutdownHook] INFO  org.eclipse.jetty.server.handler.ContextHandler#?:? -Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@5b72b13a{application,/vm-service,[file:///C:/Users/%E9%A2%9C%E8%B1%AA%E7%94%B7/AppData/Local/Temp/jetty-docbase.9011.1533347368098452577/, jar:file:/D:/data/.m2/org/webjars/swagger-ui/4.18.2/swagger-ui-4.18.2.jar!/META-INF/resources],STOPPED}
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.841 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -HikariPool-1 - Shutdown initiated...
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.844 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -HikariPool-1 - Shutdown completed.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.847 [SpringApplicationShutdownHook] INFO  org.springframework.scheduling.quartz.SchedulerFactoryBean#?:? -Shutting down Quartz Scheduler
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.847 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service shutting down.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.847 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service paused.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.847 [SpringApplicationShutdownHook] INFO  org.quartz.core.QuartzScheduler#?:? -Scheduler vm-service_$_vm-service shutdown complete.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.848 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#close:350 -DatebookHikariCP - Shutdown initiated...
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.848 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -DatebookHikariCP - Shutdown completed.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.848 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -HikariPool-2 - Shutdown initiated...
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.849 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -HikariPool-2 - Shutdown completed.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.851 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -DatebookHikariCP - Shutdown initiated...
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.851 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource#?:? -DatebookHikariCP - Shutdown completed.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.851 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.zaxxer.hikari.pool.PoolBase#?:? -DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6dd696e8 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:41.914 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Shutting down DiscoveryClient ...
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:44.918 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator#?:? -DataSource health check failed
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:158)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: DatebookHikariCP - Interrupted during connection acquisition
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 19 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:906)
	at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:164)
	... 24 common frames omitted
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:44.921 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator#?:? -DataSource health check failed
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:158)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (DatebookHikariCP) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 19 common frames omitted
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:44.922 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#unregister:915 -Unregistering ...
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:44.922 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator#?:? -DataSource health check failed
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:158)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-2) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 19 common frames omitted
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:44.934 [DiscoveryClient-InstanceInfoReplicator-0] WARN  org.springframework.cloud.health.RefreshScopeHealthIndicator#?:? -Health check failed
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'refreshScope': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:2056)
	at org.springframework.cloud.health.RefreshScopeHealthIndicator.doHealthCheck(RefreshScopeHealthIndicator.java:48)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:162)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:147)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:44.940 [DiscoveryClient-InstanceInfoReplicator-0] WARN  com.netflix.discovery.DiscoveryClient#?:? -Exception from healthcheckHandler.getStatus, setting status to DOWN
reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
	at reactor.core.Exceptions.propagate(Exceptions.java:408)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1710)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.processContributor(EurekaHealthCheckHandler.java:173)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:150)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:140)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:129)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1384)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	... 14 common frames omitted
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:44.940 [DiscoveryClient-InstanceInfoReplicator-0] INFO  com.netflix.discovery.DiscoveryClient#register:817 -DiscoveryClient_VM-SERVICE/M444444A1:vm-service:9011: registering service...
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:44.959 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -DiscoveryClient_VM-SERVICE/M444444A1:vm-service:9011 - deregister  status: 200
[12540] [application.name_IS_UNDEFINED] 2025-07-29 22:12:44.963 [SpringApplicationShutdownHook] INFO  com.netflix.discovery.DiscoveryClient#?:? -Completed shut down of DiscoveryClient
